# Generated by Django 4.2.14 on 2024-08-22 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Albums',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название альбома')),
                ('photo', models.ImageField(blank=True, default=None, null=True, upload_to='photos/album_photos/', verbose_name='Обложка альбома')),
                ('public', models.BooleanField(default=True, verbose_name='Публичный альбом')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название картинки')),
                ('photo', models.ImageField(upload_to='photos/images/', verbose_name='Изображение')),
                ('content', models.TextField(blank=True, max_length=250, verbose_name='Подпись к картинке')),
                ('public', models.BooleanField(default=True, verbose_name='Публичная картинка')),
                ('album', models.ManyToManyField(related_name='images', to='main_pages.albums', verbose_name='Альбомы')),
            ],
        ),
    ]
