# Generated by Django 4.2.14 on 2024-08-28 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='create',
            field=models.DateField(auto_now_add=True),
        ),
    ]
