# Generated by Django 4.2.14 on 2024-08-22 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='public_email',
            field=models.BooleanField(default=True, verbose_name='Отобразить почту'),
        ),
    ]
